apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: ecommerce-secrets

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: ecommerce-secrets
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: ecommerce/prod
