{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
  EMAIL_USER: {{ .Values.secrets.emailUser | quote }}
  EMAIL_PASS: {{ .Values.secrets.emailPass | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendUrl | quote }}
  PORT: "3000"
  NODE_ENV: "production"
{{- end }}