apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml

images:
  - name: oziii/ecommerce-frontend
    newTag: k8s-v1
  - name: oziii/ecommerce-backend
    newTag: k8s-v1
