apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-assets-pv-node2
  labels:
    type: local
    node: node2
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/ecommerce/assets
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-10-0-2-10   # <-- Replace with your actual Node 2 hostname``