backend:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

frontend:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"

hpa:
  enabled: false

secrets:
  frontendUrl: "http://localhost:8080"