apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecommerce-frontend-netpol
  namespace: ecommerce
spec:
  podSelector:
    matchLabels:
      app: ecommerce-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from NGINX Ingress Controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
    # Allow traffic from same namespace (service-to-service)
    - from:
        - namespaceSelector:
            matchLabels:
              name: ecommerce
      ports:
        - protocol: TCP
          port: 80
  egress:
    # Allow DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS to anywhere (for Unsplash images)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP to anywhere
    - to: []
      ports:
        - protocol: TCP
          port: 80